site_name: fouriest
repo_url: https://github.com/f0uriest/fouriest.net
edit_uri: edit/main/docs/

nav:
  - Home: 'index.md'
  - Publications: 'publications.md'

plugins:
  - search
  - git-revision-date

theme:
  name: terminal
  palette: dark
  features:
    - revision.date
    - revision.history

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js